# Dangerous Dave (John Romero) style VERY barebones game via pygame
# Generated by ChatGPT AI
# 

import pygame

# Initialize Pygame
pygame.init()

# Set the window dimensions
window_width = 640
window_height = 480

# Create the window
window = pygame.display.set_mode((window_width, window_height))

# Load the player sprite
player_image = pygame.image.load("dave.png")
player_rect = player_image.get_rect()

# Set the initial player position
player_rect.x = window_width // 2
player_rect.y = window_height // 2

# Create a clock to track the time
clock = pygame.time.Clock()

# Main game loop
while True:
    # Check for events
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()

    # Get the pressed keys
    keys = pygame.key.get_pressed()

    # Update the player position based on the pressed keys
    if keys[pygame.K_LEFT]:
        player_rect.x -= 5
    if keys[pygame.K_RIGHT]:
        player_rect.x += 5
    if keys[pygame.K_UP]:
        player_rect.y -= 5
    if keys[pygame.K_DOWN]:
        player_rect.y += 5

    # Clear the window
    window.fill((0, 0, 0))

    # Draw the player on the window
    window.blit(player_image, player_rect)

    # Update the display
    pygame.display.flip()

    # Limit the frame rate
    clock.tick(60)

